// js/config.js
// Table column definitions cho DRP scripts
// Khớp với config.py::TABLE_COLUMNS

// drep_list columns
exports.drep_list = [
  'drep_id',
  'given_name',
  'content_url',
  'https_uris',
  'amount',
  'active_epoch',
];

// drep_info columns
exports.drep_info = [
  'drep_id',
  'given_name',
  'content_url',
  'https_uris',
  'amount',
  'active_epoch',
  'stake_address',
];

// drep_delegators columns
exports.drep_delegators = [
  'id',
  'drep_id',
  'stake_address',
  'stake_address_hex',
  'script_hash',
  'amount_lovelace',
  'epoch_no',
  'timestamp',
  'timestamp_epoch',
];

// proposals columns (reference)
exports.proposals = [
  'proposal_id',
  'title',
  'status',
  'proposed_epoch',
  'expiration',
  'activities_table_name',
  'abstract',
  'author_name',
  'epoch_no',
  'description',
  'budget_requested',
  'data_fetched_at',
  'created_at',
  'updated_at',
];

// ── Aggregated export ─────────────────────────────────────────────
// Các sync script dùng dạng: const { TABLE_COLUMNS } = require('./config')
// Khớp với config.py::TABLE_COLUMNS
const TABLE_COLUMNS = {
  drep_list: [
    'id',
    'drep_id',
    'created_at',
    'updated_at',
  ],
  drep_info: [
    'id',
    'drep_id',
    'amount',
    'active_epoch',
    'last_active_epoch',
    'url',
    'payment_address',
    'given_name',
    'content_url',
    'https_uris',
    'metadata_fetched_at',
    'created_at',
    'updated_at',
  ],
  drep_delegators: [
    'id',
    'drep_id',
    'stake_address',
    'stake_address_hex',
    'script_hash',
    'epoch_no',
    'amount_lovelace',
    'amount_ada',
    'is_current',
    'delegation_type',
    'first_seen_epoch',
    'last_seen_epoch',
    'delegation_count',
    'is_whale',
    'is_exchange',
    'created_at',
    'updated_at',
  ],
  proposals: [
    'id',
    'proposal_id',
    'title',
    'abstract',
    'first_reference_uri',
    'author_name',
    'proposal_index',
    'proposal_tx_hash',
    'proposed_epoch',
    'expiration',
    'proposal_type',
    'epoch_no',
    'status',
    'description',
    'budget_requested',
    'voting_start_date',
    'voting_end_date',
    'implementation_start_date',
    'implementation_end_date',
    'documentation_urls',
    'discussion_urls',
    'data_fetched_at',
    'created_at',
    'updated_at',
    'activities_table_created',
    'activities_table_name',
    'abstract_summary',
    'slug',
  ],
  proposal_voting_summary: [
    'id',
    'proposal_id',
    'proposal_type',
    'epoch_no',
    'drep_yes_votes_cast',
    'drep_active_yes_vote_power',
    'drep_yes_vote_power',
    'drep_yes_pct',
    'drep_no_votes_cast',
    'drep_active_no_vote_power',
    'drep_no_vote_power',
    'drep_no_pct',
    'drep_abstain_votes_cast',
    'drep_active_abstain_vote_power',
    'drep_abstain_vote_power',
    'drep_always_abstain_vote_power',
    'drep_always_no_confidence_vote_power',
    'pool_yes_votes_cast',
    'pool_active_yes_vote_power',
    'pool_yes_vote_power',
    'pool_yes_pct',
    'pool_no_votes_cast',
    'pool_active_no_vote_power',
    'pool_no_vote_power',
    'pool_no_pct',
    'pool_abstain_votes_cast',
    'pool_active_abstain_vote_power',
    'pool_passive_always_abstain_votes_assigned',
    'pool_passive_always_abstain_vote_power',
    'pool_passive_always_no_confidence_votes_assigned',
    'pool_passive_always_no_confidence_vote_power',
    'committee_yes_votes_cast',
    'committee_yes_pct',
    'committee_no_votes_cast',
    'committee_no_pct',
    'committee_abstain_votes_cast',
    'data_fetched_at',
    'created_at',
    'updated_at',
  ],
  ga_table: [
    'id',
    'block_time',
    'voter_role',
    'voter_id',
    'vote',
    'meta_url',
    'comment',
    'processed_at',
    'created_at',
    'updated_at',
  ],
};

module.exports.TABLE_COLUMNS = TABLE_COLUMNS;

// ga_* table columns (reference)
exports.ga_table = [
  'id',
  'block_time',
  'voter_role',
  'voter_id',
  'vote',
  'meta_url',
  'comment',
  'processed_at',
  'created_at',
  'updated_at',
];

// proposal_voting_summary columns
exports.proposal_voting_summary = [
  'proposal_id',
  'epoch_no',
  'drep_yes_votes_cast',
  'drep_no_votes_cast',
  'drep_active_yes_vote_power',
  'drep_yes_vote_power',
  'drep_yes_pct',
  'drep_no_vote_power',
  'drep_no_pct',
  'drep_abstain_votes_cast',
  'drep_active_abstain_vote_power',
  'drep_always_abstain_vote_power',
  'drep_always_no_confidence_vote_power',
  'pool_yes_votes_cast',
  'pool_active_yes_vote_power',
  'pool_yes_vote_power',
  'pool_yes_pct',
  'pool_no_votes_cast',
  'pool_active_no_vote_power',
  'pool_no_vote_power',
  'pool_no_pct',
  'pool_abstain_votes_cast',
  'pool_active_abstain_vote_power',
  'committee_yes_votes_cast',
  'committee_yes_pct',
  'committee_no_votes_cast',
  'committee_no_pct',
  'committee_abstain_votes_cast',
  'data_fetched_at',
  'created_at',
  'updated_at',
];